### ISSUE TITLE
Angular 6

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [angular/preboot#85]
Is there some plans to make it Angular 6 and rxjs comaptible?
If this is the case - when?

**Comment by CaerusKaru** [comment]
Sure, I'll try to get a PR in this week (alternatively, you are more than welcome to submit one as well!)

**Comment by vytautas-pranskunas-** [comment]
If i new how it works - i would :)  already helped migrating 2 libraries to NG6 but i am afraid not this time :( however i will be waiting for migration :)

**Comment by wapisgroup** [comment]
Hi guys, 
I'm having the fix ready to push, unfortunately, I'm not able to push the branch due to the following error (Failed with error: unable to access 'https://github.com/angular/preboot.git/': The requested URL returned error: 403). Sorry, I've never contributed to a public repo, if you can point me how to fix it I'll push the code for review. Thanks and sorry for OT issue in the stream.

**Comment by CaerusKaru** [comment]
@wapisgroup You need to create a fork of the repository and push to that. Then you can open a pull request from the fork to this repo.

**Comment by CaerusKaru** [comment]
Closed by #87, and thanks to @wapisgroup for their help in putting together the PR.
